import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    fontFamily: "Arial, sans-serif",
    background: "#eef6f5",
    minHeight: "100vh",
    padding: "clamp(12px, 3vw, 24px)",
    boxSizing: "border-box",
  },
  card: {
    background: "#ffffff",
    borderRadius: 8,
    padding: "clamp(16px, 3vw, 28px)",
    boxShadow: "0 18px 45px rgba(3, 32, 42, 0.10)",
    maxWidth: 1440,
    margin: "0 auto",
    width: "100%",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  row: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
  },
  input: {
    width: "100%",
    padding: 10,
    borderRadius: 8,
    border: "1px solid #b9d3d1",
    fontSize: 16,
    boxSizing: "border-box",
    minWidth: 0,
    background: "#fbfefd",
    color: "#092934",
  },
  button: {
    background: "#0f766e",
    color: "#ffffff",
    border: "none",
    padding: "10px 14px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 700,
    maxWidth: "100%",
    whiteSpace: "normal",
    boxShadow: "0 8px 18px rgba(15, 118, 110, 0.20)",
  },
  secondaryButton: {
    background: "#e6f3f1",
    color: "#06323f",
    border: "1px solid #b9d3d1",
    padding: "10px 14px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 700,
    maxWidth: "100%",
    whiteSpace: "normal",
  },
  title: {
    marginTop: 0,
    color: "#06323f",
  },
  section: {
    border: "1px solid #d7e6e4",
    borderRadius: 8,
    padding: 14,
    marginTop: 14,
    background: "#fbfefd",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  small: {
    color: "#5e7378",
    fontSize: 13,
  },
  error: {
    padding: 10,
    borderRadius: 8,
    background: "#fee2e2",
    color: "#991b1b",
    marginBottom: 12,
  },

  cardTitle: {
    marginTop: 0,
    marginBottom: 12,
    color: "#06323f",
  },
  sectionTitle: {
    marginTop: 0,
    marginBottom: 10,
    color: "#06323f",
  },
  field: {
    marginBottom: 14,
  },
  label: {
    display: "block",
    marginBottom: 6,
    fontWeight: 600,
    color: "#244a54",
  },
  textarea: {
    width: "100%",
    minHeight: 90,
    padding: 10,
    borderRadius: 8,
    border: "1px solid #b9d3d1",
    resize: "vertical",
    fontSize: 14,
    boxSizing: "border-box",
    background: "#fbfefd",
    color: "#092934",
  },
  primaryButton: {
    background: "#0f766e",
    color: "#ffffff",
    border: "none",
    padding: "10px 14px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 700,
  },
  removeButton: {
    background: "#dc2626",
    color: "#fff",
    border: "none",
    padding: "6px 10px",
    borderRadius: 8,
    cursor: "pointer",
    marginTop: 8,
    fontSize: 12,
  },
  formInfo: {
    padding: 12,
    borderRadius: 12,
    background: "#f5fbfa",
    marginBottom: 16,
    border: "1px solid #d7e6e4",
  },
  formBlock: {
    border: "1px solid #d7e6e4",
    borderRadius: 8,
    padding: 14,
    marginBottom: 16,
    background: "#ffffff",
  },
  questionEditRow: {
    display: "grid",
    gridTemplateColumns: "38px minmax(0, 1fr) 38px",
    gap: 10,
    alignItems: "stretch",
    marginBottom: 8,
  },
  questionDragHandle: {
    border: "1px solid #b9d3d1",
    borderRadius: 8,
    background: "#e6f3f1",
    color: "#244a54",
    cursor: "grab",
    fontWeight: 800,
    fontSize: 16,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none",
    minHeight: 42,
  },
  iconButton: {
    border: "1px solid #fecaca",
    borderRadius: 8,
    background: "#fef2f2",
    color: "#b91c1c",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    padding: 0,
  },
  questionDragHandleActive: {
    cursor: "grabbing",
    background: "#ccfbf1",
    borderColor: "#2dd4bf",
    color: "#0f766e",
  },
  questionTitle: {
    fontWeight: 700,
    fontSize: 16,
    marginBottom: 10,
    color: "#06323f",
  },
  answerRow: {
    display: "flex",
    gap: 8,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  photoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 12,
    marginTop: 12,
  },
  photoCard: {
    border: "1px solid #d7e6e4",
    borderRadius: 8,
    padding: 10,
    background: "#fbfefd",
  },
  photoPreview: {
    width: "100%",
    height: 110,
    objectFit: "cover",
    borderRadius: 10,
    display: "block",
  },
  bottomActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 20,
    flexWrap: "wrap",
  },
};
