# Copy to /etc/logrotate.d/inspectria and update the path if needed.
/var/www/inspectria/logs/*.log {
  daily
  rotate 14
  size 10M
  missingok
  notifempty
  compress
  delaycompress
  copytruncate
}
